### PR TITLE
Update to Visual Studio 2015 / C# 6

### PR DESCRIPTION
**Pull request by kitforbes**
Optional PR to update the library to C# 6 with a VS 2015 solution. Also removes the old NuGet approach for auto restore and corrects some code consistencies. I won't be hurt if this isn't accepted as you may not want to move beyond VS 2012 yet.

### CODE REVIEW

**Comment by Astro03** [comment]
Darn, I have no updated my company from VS2013 to VS2016. :(  If we accept this pull, then i won't be able to work on it anymore. 

Once we update, i'll accept it though.. Awesome job btw :)

**Comment by Astro03** [comment]
@kitforbes there is a merge conflict, can you fix so i can accept pull? :)  thanks.  (because of you, i'm going to update my computers at work)

**Comment by andrewcartwright1** [comment]
Sorry about that :sweat_smile:

**Comment by kitforbes** [comment]
No problem at all @andrewcartwright1.

**Pull request merged**
