### PR TITLE
Fix auth

### PR DESCRIPTION
**Pull request by fushinoryuu**
This PR fixes the auth issue mentioned in #58:

- Fixed a bug with the client not being able to authenticate.
- Added a testing project.

### CODE REVIEW

**Comment by fushinoryuu** [comment]
@Astro03 please review when you have a sec

**Comment by Astro03** [comment]
@fushinoryuu I just merged #60, does having both your changes and theirs break auth again (because it would add two "Basic" to the header - or am i reading this incorrectly?)

**Comment by fushinoryuu** [comment]
@Astro03 I didn't realize that he had submitted a PR.

It would break again, so let me merge his changes into mine and I'll let you know when its ready for another review. Thanks!

**Comment by Astro03** [comment]
Dang, that's what I thought. 

I merged his changes thinking it was yours. Sorry. 

I think yours is cleaner but I"m good with either approach.

**Comment by Astro03** [comment]
IS this good to go? I see you took his approach for the auth.

**Comment by fushinoryuu** [comment]
Yes, please merge when you have a sec

**Pull request merged**
